name: Coq CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OCaml and OPAM
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0

      - name: Set up OPAM and install dependencies
        run: |
          opam init -y --bare
          opam switch create . 4.14.0
          eval $(opam env)
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam update

          # Install Coq and required packages
          opam install -y coq.8.18.0 coq-stdpp.1.9.0 coq-itauto coq-equations coq-vlsm.1.3

      - name: Build project
        run: |
          eval $(opam env)
          make
